import pytest
from app.services.ship30_skill import build_ship30_prompt, SHIP30_SYSTEM_PROMPT
from app.services.agent import agent_service

def test_ship30_prompt_structure():
    mock_chunks = [
        {
            "guest": "Shreyas Doshi",
            "title": "The Art of Product Management",
            "timestamp": "00:24:50",
            "text": "If you do a pre-mortem right, you will not have to do an ugly post-mortem."
        }
    ]
    prompt = build_ship30_prompt("Why pre-mortems save product teams", mock_chunks)
    
    assert "Ship 30 for 30" in prompt
    assert "Shreyas Doshi" in prompt
    assert "00:24:50" in prompt
    assert "~1,250-word" in prompt

def test_ship30_system_prompt_framework():
    assert "HEADLINE & HOOK" in SHIP30_SYSTEM_PROMPT
    assert "1-3-1 CADENCE" in SHIP30_SYSTEM_PROMPT
    assert "SKIMMABLE VISUAL ARCHITECTURE" in SHIP30_SYSTEM_PROMPT
    assert "ACTIONABLE PILLARS" in SHIP30_SYSTEM_PROMPT
    assert "1,250 words" in SHIP30_SYSTEM_PROMPT

def test_artifact_parsing_ship30():
    sample_agent_output = """
Here is your essay based on Lenny's Podcast:

:::artifact{id="essay-123" type="markdown" title="Ship 30 Essay: The Power of Pre-Mortems"}
# The Power of Pre-Mortems

Most product launches fail quietly before they ever ship.

Here is why: Teams mistake optimism for alignment.
They run post-mortems instead of proactive diagnosis.
It costs companies millions in wasted roadmaps.

## 1. Tigers vs Paper Tigers
As Shreyas Doshi explains on Lenny's Podcast...
:::
"""
    artifacts = agent_service._parse_artifacts(sample_agent_output, "session-test-1")
    assert len(artifacts) == 1
    art = artifacts[0]
    # Server regenerates ids (models repeat ids like "essay" across messages,
    # which would violate the primary key) - but must still be non-empty.
    assert art.id
    assert art.artifact_type == "markdown"
    assert "Pre-Mortems" in art.title
    assert "Shreyas Doshi" in art.content

def test_artifact_parsing_generates_unique_ids():
    """Repeated model-supplied ids must not collide (primary key safety)."""
    sample = """
:::artifact{id="essay" type="markdown" title="First Essay"}
# First
:::
:::artifact{id="essay" type="markdown" title="Second Essay"}
# Second
:::
"""
    artifacts = agent_service._parse_artifacts(sample, "session-test-1")
    assert len(artifacts) == 2
    assert artifacts[0].id != artifacts[1].id

def test_suggestions_generator():
    from app.schemas.chat_schemas import CitationItem
    citations = [
        CitationItem(
            guest="Shreyas Doshi",
            title="Pre-mortems",
            youtube_url="https://youtube.com/watch?v=123",
            timestamp="00:15:00",
            quote="Tigers eat you.",
            relevance_score=0.85
        )
    ]
    suggestions = agent_service._generate_suggestions("Tell me about pre-mortems", citations)
    assert len(suggestions) > 0
    assert any("Tigers" in s or "Shreyas" in s for s in suggestions)

def test_suggestions_elena_verna():
    from app.schemas.chat_schemas import CitationItem
    citations = [
        CitationItem(
            guest="Elena Verna",
            title="B2B Growth Loops",
            youtube_url="https://youtube.com/watch?v=456",
            timestamp="00:10:00",
            quote="Growth loops compound.",
            relevance_score=0.75
        )
    ]
    suggestions = agent_service._generate_suggestions("Elena Verna growth loops", citations)
    assert len(suggestions) > 0
    assert any("loop" in s.lower() or "verna" in s.lower() for s in suggestions)

def test_artifact_parsing_single_line_and_malformed():
    # Test single-line format often generated by 1B/small LLMs
    single_line = 'Here is your framework: :::artifact{id="406a836f" type="markdown" title="Creator Economy Essentials"} Focus on value creation and build trust with social proof.::: Hope this helps!'
    artifacts = agent_service._parse_artifacts(single_line, "session-test-2")
    assert len(artifacts) == 1
    assert artifacts[0].title == "Creator Economy Essentials"
    assert "Focus on value creation" in artifacts[0].content
    assert ":::" not in artifacts[0].content

    # Test trailing dot-ellipsis delimiter
    trailing_dots = ':::artifact{id="abc" type="markdown" title="Strategy"} Quick plan ...:::'
    artifacts2 = agent_service._parse_artifacts(trailing_dots, "session-test-3")
    assert len(artifacts2) == 1
    assert artifacts2[0].title == "Strategy"
    assert artifacts2[0].content == "Quick plan"

def test_artifact_parsing_mixed_brace_and_bare_attrs():
    # Transcript 05's documented edge case: attrs split between {...} and the
    # rest of the opening line. type/title after the brace must survive.
    sample = """:::artifact{id="b1a4f5eb"} type="markdown" title="Ship 30: Pre-Mortem Playbook"
# Pre-Mortem Playbook

Body content grounded in Shreyas Doshi's advice.
:::"""
    artifacts = agent_service._parse_artifacts(sample, "sess-mixed")
    assert len(artifacts) == 1
    assert artifacts[0].artifact_type == "markdown"
    assert artifacts[0].title == "Ship 30: Pre-Mortem Playbook"
    assert "Pre-Mortem Playbook" in artifacts[0].content

    html_sample = """:::artifact{id="w1"} type="html" title="PMF Calculator"
<!DOCTYPE html><html><body>calc</body></html>
:::"""
    artifacts2 = agent_service._parse_artifacts(html_sample, "sess-mixed-2")
    assert len(artifacts2) == 1
    assert artifacts2[0].artifact_type == "html"
    assert artifacts2[0].title == "PMF Calculator"


def test_is_greeting_or_meta():
    assert agent_service.is_greeting_or_meta("hi") is True
    assert agent_service.is_greeting_or_meta("Hello, who are you?") is True
    assert agent_service.is_greeting_or_meta("who are you") is True
    assert agent_service.is_greeting_or_meta("what can you do") is True
    assert agent_service.is_greeting_or_meta("hey there") is True
    assert agent_service.is_greeting_or_meta("hlo") is True
    
    # Must NOT treat actual domain questions as greetings
    assert agent_service.is_greeting_or_meta("hi, what does Shreyas Doshi say about pre-mortems?") is False
    assert agent_service.is_greeting_or_meta("explain growth loops") is False

def test_intent_routing_explicit_skill_wins():
    """Explicit UI skill selection must beat text heuristics."""
    # No keywords at all, but skill=artifact must force HTML mode
    assert agent_service._detect_intent("make a survey tool", "artifact") == {"ship30": False, "html": True}
    # Keyword 'ship 30' inside chat mode triggers ship30...
    assert agent_service._detect_intent("write a ship 30 essay on retention", None) == {"ship30": True, "html": False}
    # ...but a domain question mentioning 'shipping' must NOT trigger ship30.
    assert agent_service._detect_intent("what do guests say about shipping fast", None) == {"ship30": False, "html": False}
    # 'HTML' must match on word boundaries only.
    assert agent_service._detect_intent("build a html calculator", None) == {"ship30": False, "html": True}
    # ship30 skill never doubles as html even if the topic mentions dashboards.
    assert agent_service._detect_intent("ship 30 essay about dashboards", "ship30") == {"ship30": True, "html": False}

@pytest.mark.asyncio
async def test_process_chat_greeting():
    events = []
    async for event in agent_service.process_chat("Hello, who are you?", session_id="sess-greeting"):
        events.append(event)
    
    event_types = [e["type"] for e in events]
    assert "status" in event_types
    assert "citations" in event_types
    assert "token" in event_types
    assert "done" in event_types
    
    # Citations must be empty for casual greetings
    citations_event = next(e for e in events if e["type"] == "citations")
    assert citations_event["data"] == []
    
    # Check that it streamed the Lenny Growth Assistant greeting
    tokens = "".join(e["data"] for e in events if e["type"] == "token")
    assert "The Lenny Growth Assistant" in tokens
    assert "Lenny's Podcast" in tokens


@pytest.mark.asyncio
async def test_ship30_convert_button_long_message_not_rejected(monkeypatch):
    """The 'Turn into Ship 30 for 30 Essay' button pastes the full grounded
    answer (~450 chars) as the message. The retrieval gate must not
    force-reject this in-domain conversion request (Phase 4 regression)."""
    from app.services.llm_gateway import llm_gateway

    grounded = (
        "Based on the retrieved podcast context, the key framework here is\n\n"
        "## Pre-Mortems: Tigers, Paper Tigers, and Elephants\n\n"
        "Shreyas Doshi distinguishes three failure classes before launch. First, **Tigers** are the known, actively discussed risks. "
        "Second, **Paper Tigers** are risks the team talks about but nobody is actually mitigating. "
        "Third, **Elephants in the room** are the uncomfortable truths everyone knows but nobody names. "
        "Running a pre-mortem surfaces all three so the team can act while there is still time."
    )
    message = f"Convert this strategic insight into a Ship 30 for 30 essay:\n\n{grounded[:450]}"

    async def fake_validate(*args, **kwargs):
        return None

    async def fake_stream(messages, provider=None, model=None):
        yield "Ship 30 essay content."

    monkeypatch.setattr(llm_gateway, "validate_provider", fake_validate)
    monkeypatch.setattr(llm_gateway, "stream_chat", fake_stream)

    events = []
    async for event in agent_service.process_chat(message, skill="ship30", session_id="sess-ship30-convert"):
        events.append(event)

    citations_event = next((e for e in events if e["type"] == "citations"), None)
    assert citations_event is not None
    assert len(citations_event["data"]) > 0, "in-domain ship30 conversion must pass the grounding gate"
    done = next(e for e in events if e["type"] == "done")
    assert done["data"].get("rejection") is not True

